import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card/Card'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <h2>Index.tsx</h2>
        <Card unityName="Unidade de saúde de teste"
          sync={false}
          anydeskCount={2}
          cnes="256484"/>
      </main>
      
    </div>
  )
}
